ALTER TABLE "user" ADD COLUMN IF NOT EXISTS pending_email VARCHAR(255);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS verification_token VARCHAR(255);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS verification_expires TIMESTAMPTZ;
